### ISSUE TITLE
The controller App\Http\Controllers\Auth\SendsPasswordResetEmails doesn't exist.

### ISSUE THREAD

**Issue by topclaudy** [beyondcode/laravel-confirm-email#16]
The documentation says to replace a trait in the controller *App\Http\Controllers\Auth\SendsPasswordResetEmails*, but this controller doesn't exist. The correct controller is *App\Http\Controllers\Auth\ForgotPasswordController*

**Comment by rickwest** [comment]
Good spot, is my mistake, #15 fixes this 👍🏻.
