### ISSUE TITLE
IDEA: Signed routes?

### ISSUE THREAD

**Issue by m1guelpf** [beyondcode/laravel-confirm-email#2]
Laravel recently added Signed Routes. Is there a need to use a database table when we can just use them?

I can PR this if you want...

**Comment by akiyamaSM** [comment]
Signed routes are available only in the L5.6 ...

**Comment by mpociot** [comment]
@m1guelpf I would like to have this configurable.
In this case we should probably also configure if someone wants to store the confirmation date in the database, as this might be quite relevant.

**Comment by william1888** [comment]
With the new GDPR rules you have to record the dates of consent for stuff like this so the database migrations are indeed useful.
