### ISSUE TITLE
How should I replace the traits?

### ISSUE THREAD

**Issue by ehsanmusavi** [beyondcode/laravel-confirm-email#22]
Sorry if this isn't an issue but I have trouble to make this package work! I also asked on stackoverflow but no one answered. How should I replace the traits? I mean what should I replace with what?

**Comment by kslr** [comment]
such as
RegisterController

```php
use BeyondCode\EmailConfirmation\Traits\RegistersUsers;

class RegisterController extends Controller
{
    /*
    |--------------------------------------------------------------------------
    | Register Controller
    |--------------------------------------------------------------------------
    |
    | This controller handles the registration of new users as well as their
    | validation and creation. By default this controller uses a trait to
    | provide this functionality without requiring any additional code.
    |
    */
    use RegistersUsers;

```

**Comment by ehsanmusavi** [comment]
I replaced these lines: 

`use App\User;`
`use App\Http\Controllers\Controller;`
`use Illuminate\Support\Facades\Hash;`
`use Illuminate\Support\Facades\Validator;`
`use Illuminate\Foundation\Auth\RegistersUsers;`

with:
`use BeyondCode\EmailConfirmation\Traits\RegistersUsers;`

Is this right?
I'm getting `Class 'App\Http\Controllers\Auth\Controller' not found` error!

**Comment by kslr** [comment]
@ehsanmusavi  
remove ```use Illuminate\Foundation\Auth\RegistersUsers;```
add ```use BeyondCode\EmailConfirmation\Traits\RegistersUsers;```

**Comment by ehsanmusavi** [comment]
Thank you, @kslr

**Comment by kslr** [comment]
@ehsanmusavi please close

**Comment by kslr** [comment]
@rickwest  @mpociot please close issue

**Comment by kslr** [comment]
@rickwest @mpociot please close issue

**Comment by kslr** [comment]
@mpociot @sschlein @ehsanmusavi
