### ISSUE TITLE
Users can't login afer logout

### ISSUE THREAD

**Issue by ehsanmusavi** [beyondcode/laravel-confirm-email#26]
Sometimes my users have this issue that when they logout, they can't login back again! They get "These credentials do not match our records." error while they are registered and confirmed their registration! I think this is something to do with sessions maybe. Did you ever had this problem? How can I solve it?

**Comment by mpociot** [comment]
This should usually come from the laravel authentication. I don't see how this package could affect that, as it has it's own error messages regarding verification.
