### ISSUE TITLE
Laraval update

### ISSUE THREAD

**Issue by mafzalzadeh** [beyondcode/laravel-confirm-email#28]
I cannot update Laravel to 5.7 it's might conflict with these codes.
Is it any way to update?

**Comment by rbmcgowan** [comment]
- Installation request for beyondcode/laravel-confirm-email ^1.4 -> satisfiable by beyondcode/laravel-confirm-email[1.4.0].
    - Conclusion: remove laravel/framework v5.7.8
    - Conclusion: don't install laravel/framework v5.7.8
    - beyondcode/laravel-confirm-email 1.4.0 requires illuminate/notifications ~5.5.0|~5.6.0 -> satisfiable by illuminate/notifications[5.5.x-dev, 5.6.x-dev].
    - don't install illuminate/notifications 5.5.x-dev|don't install laravel/framework v5.7.8

**Comment by kslr** [comment]
@mpociot  plase post a new tag

**Comment by mafzalzadeh** [comment]
@mpociot 
After your commit to dev-master problem solved.
Thanks

**Comment by danmeade** [comment]
@mpociot Do you have an ETA on this?

Installation still seems to fail on v5.7.* (I'm running v5.7.19)
