### ISSUE TITLE
Everything seems to work except creating confirmation_code and sending e-mail

### ISSUE THREAD

**Issue by mreid2005** [beyondcode/laravel-confirm-email#29]
I'm running a dockerized version of laravel and I've been attempting to get this functionality to work with.
Laravel Framework 5.6.39 
Ubuntu 16.04
DebugBar doesn't show any problems, 

composer require ... worked fine
vendor:publish ... worked fine and migration ran no problem.

added the routes.

updated the Controllers.
added the alert blocks.

rebuilt, and when I try to login, it warns that i'm not confirmed, as expected.
when I hit resend verification email, it returns me to login, and there are no apparent errors or anything otherwise logged in debugbar.

if I attempt to create a new account same thing.
no confirmation code in users table.
and no e-mail
and no error.

I will be happy to share whatever may be helpful, I've gone over everything numerous times, and just not sure what I'm missing.

Any help is appreciated, Thank you.

Michael

**Comment by kslr** [comment]
Mail driver log?

**Comment by mreid2005** [comment]
So I rolled back to a snapshot, on my non - docker testing box, and tried the installation steps 
Something isn't quite right.
I'm on ubuntu, with laravel 5.6.39:
`composer require beyondcode/laravel-confirm-email`
runs with no errors

`php artisan vendor:publish --provider=BeyondCode\EmailConfirmation\EmailConfirmationServiceProvider`
comes back with 
`Publishing complete`

And run the migrations:
`php artisan migrate`
  returns -> nothing to migrate
the migration stub doesn't exist in database/migrations

which leads me to believe the configuration isn't running as expected.

**Comment by mreid2005** [comment]
figured it out.
