### ISSUE TITLE
Is this package still relevant in Laravel 5.7 which offers an email verification feature? 

### ISSUE THREAD

**Issue by topclaudy** [beyondcode/laravel-confirm-email#31]
Is this package still relevant in Laravel 5.7 which offers email verification support? https://laravel.com/docs/5.7/verification

**Comment by LonnyX** [comment]
I was using this package but when I upgraded to 5.7, I replaced it with the built-in one.
It's not the exact same behavior but both are good :)

**Comment by kslr** [comment]
I spent about a day adjusting all the code.
