### ISSUE TITLE
How do you change the views for the email 

### ISSUE THREAD

**Issue by abrhambas01** [beyondcode/laravel-confirm-email#33]
I'm wondering where can I change the views so that I can replace the default one with my own. ?

**Comment by kslr** [comment]
Do you speak mail?
https://laravel.com/docs/5.7/mail
https://github.com/beyondcode/laravel-confirm-email/blob/master/src/Notifications/ConfirmEmail.php#L31

**Comment by abrhambas01** [comment]
I mean this one, I'l change this to somewhat like this : 

![image](https://user-images.githubusercontent.com/12043306/50558553-5d807d00-0d2a-11e9-82ff-f20c0386e8a7.png)


to this one 


![image](https://user-images.githubusercontent.com/12043306/50558587-90c30c00-0d2a-11e9-8722-713f2f6df6ed.png)

**Comment by abrhambas01** [comment]
Oh yeah sir, let me check on the docs, thank you so much you've been helpful
