### ISSUE TITLE
Migrations not published

### ISSUE THREAD

**Issue by tombutterworth** [beyondcode/laravel-confirm-email#4]
Hi

The vendor publish command does not seem to generate a migration file currently. 

`php artisan vendor:publish --provider=BeyondCode\EmailConfirmation\EmailConfirmationServiceProvider`

"Publishing complete."

`php artisan migrate`

"Nothing to migrate."

Thanks

Tom

**Comment by mpociot** [comment]
You probably need to escape the backslashes.

```bash
php artisan vendor:publish --provider=BeyondCode\\EmailConfirmation\\EmailConfirmationServiceProvider
```

I'll update the readme.

**Comment by roelmagdaleno** [comment]
Please, update the README, I had this issue too. Thanks.

**Comment by soheilrt** [comment]
the same issue happened to me:/
