### ISSUE TITLE
Password reset bypasses confirmation

### ISSUE THREAD

**Issue by tombutterworth** [beyondcode/laravel-confirm-email#6]
Hi

Currently if you register as a new user, do not use the confirmation email link, but then use the Auth password retrieval you can reset your password and log in successfully without email confirmation preventing log in.

I don't see an issue in this, in the fact that the user is essentially having to receive an email and action it to get the reset link.

However it is a usability issue, in that the next time the user logs in, they will then get the prompt saying their email is not confirmed. Even though they had previously logged in successfully.

Perhaps it would make sense for the password reset mechanism to also perform the confirmation action if still outstanding?

Thanks

Tom

**Comment by mpociot** [comment]
Hi Tom,

Good catch. Yes the password reset mechanism should check for this too. 

Do you want to create a PR for this?

**Comment by tombutterworth** [comment]
I was going to prevent users from requesting new password if not confirmed, and then in the error message show the 'Resend activation link'. Like the log in behaviour if not confirmed yet.

In my situation silently marking the user as confirmed when they do their password update if far easier for the user. However I am aware peeps may require a concrete click of that 'Confirm email' button, so would prefer mechanism outlined above.

**Comment by rickwest** [comment]
I'd be happy to create a PR for this if you don't have time @tombutterworth ? I'm still pretty new to Laravel so this seem's like it might be a 'good first issue' for me @mpociot :smile: . No problem at all, if you are already working on a solution though!

**Comment by tombutterworth** [comment]
Feel free, it may take me a while to get round to it
