### ISSUE TITLE
Session is always null

### ISSUE THREAD

**Issue by kslr** [beyondcode/laravel-confirm-email#8]
I was rejected at login but the confirmation msg is always null.
confirmation_user_id I can get it normally.
use file session deiver
How can I do it?
```php
session([
   'confirmation_user_id' => $user->getKey()
]);

throw ValidationException::withMessages([
  'confirmation' => [
    __('confirmation::confirmation.not_confirmed', [
        'resend_link' => route('auth.resend_confirmation')
      ])
   ]
]);
```

**Comment by rickwest** [comment]
It seems ValidationException::withMessages puts the messages on the errors stack. So in your blade template, you have to access that particular message with something like $errors->confirmation->first().

**Comment by mpociot** [comment]
I modified the README to show how to handle both confirmation info messages and confirmation errors.

**Comment by kslr** [comment]
@mpociot {{ -> {!!
